import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, resolve } from 'node:path'

const currentDir = dirname(fileURLToPath(import.meta.url))
const source = readFileSync(resolve(currentDir, 'ImportModal.vue'), 'utf8')

assert.match(source, /preflightWarning/, 'ImportModal should render preflight warning details')
assert.match(source, /outlineReview/, 'ImportModal should render outline confirmation details')
assert.match(source, /确认章节结构/, 'ImportModal should label the outline confirmation view')
assert.match(source, /outline-header/, 'ImportModal should merge outline confirmation details into the modal header')
assert.match(source, /heading-count/, 'ImportModal should show the detected heading count in the compact header')
assert.match(source, /切至 L/, 'ImportModal should place the import depth control in the compact header')
assert.doesNotMatch(source, /class="outline-review-head"|class="outline-tools"/, 'ImportModal should not repeat outline metadata above the tree')
assert.match(source, /confirm-outline/, 'ImportModal should emit confirmed outline selections')
assert.match(source, /cancel-outline/, 'ImportModal should emit outline cancellation')
assert.match(source, /importDepth/, 'ImportModal should track confirmed import depth')
assert.match(source, /splitLevelById/, 'ImportModal should track per-heading split levels')
assert.match(source, /buildOutlinePlan/, 'ImportModal should emit a full outline plan')
assert.match(source, /setNodeSplitLevel/, 'ImportModal should let users change a node split level')
assert.match(source, />不切</, 'ImportModal should let users mark headings as non-split nodes')
assert.match(source, />删除</, 'ImportModal should let users delete headings from the confirmed outline')
assert.match(source, /deleted_heading_ids/, 'ImportModal should send deleted heading ids in the outline plan')
assert.match(source, /预览上下文/, 'ImportModal should let users preview the source around each heading')
assert.match(source, /context-preview-dialog/, 'ImportModal should open source context in a focused dialog')
assert.match(source, /\.context-code\.context-preview-code\s*\{[\s\S]*?max-height:\s*none/, 'Context preview text should fill the available dialog height instead of inheriting the compact inline preview limit')
assert.match(source, /openContextPreview/, 'ImportModal should open context from a dedicated button')
assert.match(source, /closeContextPreview/, 'ImportModal should close context and restore focus')
assert.doesNotMatch(source, /<span>上下文<\/span>/, 'ImportModal should keep the context action icon-only')
assert.match(source, /contextLineNumber/, 'ImportModal should preserve source line numbers in the context preview')
assert.match(source, /contextPreviewNode\.context\.heading_line/, 'ImportModal should highlight the selected heading line')
assert.match(source, /前后各最多/, 'ImportModal should explain the context window size')
assert.match(source, /visibleOutlineRows/, 'ImportModal should hide descendants of collapsed L1 groups')
assert.match(source, /toggleLevelOneGroup/, 'ImportModal should collapse one L1 group at a time')
assert.match(source, /toggleAllLevelOneGroups/, 'ImportModal should collapse or expand all L1 groups')
assert.match(source, /已收起/, 'ImportModal should show the hidden descendant count')
assert.match(source, /\{\{ node\.char_count \|\| 0 \}\} 字/, 'ImportModal should show only the character count beside each heading')
assert.match(source, /confirm-preflight/, 'ImportModal should emit a force confirmation event')
assert.match(source, /cancel-preflight/, 'ImportModal should emit a preflight cancellation event')
assert.match(source, /仍然导入/, 'ImportModal should offer a force import action for warnings')
assert.match(source, /检查导入警告/, 'ImportModal should render the import warning title in Chinese')
assert.match(source, /issue\.examples/, 'ImportModal should render issue examples separately')
assert.match(source, /chapterTypeSummary/, 'ImportModal should summarize detected chapter types')
assert.match(source, /content_type === 'exercise'/, 'ImportModal should highlight exercise chapters')
assert.match(source, /chapter-preview/, 'ImportModal should render the preflight chapter type preview')
assert.match(source, /chapter\.char_count/, 'ImportModal should show chapter character counts')
assert.match(source, /chapter\.position/, 'ImportModal should show the canonical source-order position')
assert.match(source, /chapter\.display_index/, 'ImportModal should keep display chapter numbers separate from internal fallback ids')
assert.match(source, /原文第 \{\{ chapter\.source_line \}\} 行/, 'ImportModal should identify source-line fallbacks as diagnostics')
assert.match(source, /preflightWarning\?\.severity !== 'blocked'/, 'ImportModal should not offer force import for blocked preflight errors')
assert.match(source, /导入已阻止/, 'ImportModal should clearly label blocked preflight errors')
assert.match(source, /width:\s*min\(920px,\s*calc\(100vw - 2rem\)\)/, 'ImportModal should use a wider review layout')
assert.match(source, /full\.md/, 'ImportModal should explain directory imports prefer full.md')
assert.match(source, /activeTab === 'package'/, 'ImportModal should render a Package tab')
assert.match(source, /accept="\.zip,application\/zip"/, 'ImportModal package import should accept zip files')
assert.match(source, /import-package/, 'ImportModal should emit a package import event')
assert.doesNotMatch(source, /export-package|selectedExportBookId|Export Portable Package/, 'ImportModal should keep export out of the add-book flow')

console.log('ImportModal preflight warning UI ok')
