import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, resolve } from 'node:path'

const currentDir = dirname(fileURLToPath(import.meta.url))
const source = readFileSync(resolve(currentDir, 'Library.vue'), 'utf8')
const storeSource = readFileSync(resolve(currentDir, '../stores/bookStore.js'), 'utf8')

assert.match(source, />\s*回复风格\s*</, 'Library preferences should expose localized response styles')
assert.match(source, /title="管理回复风格"/, 'Library response style button should describe its action')
assert.match(source, />\s*偏好设置\s*/, 'Library should use a concise name for the preferences menu')
assert.match(source, />\s*模型与存储\s*</, 'Library should name application settings by their contents')
assert.doesNotMatch(source, /AI Author|Agent Console|AgentConsole|handleStartAgent|showConsole/, 'Library should not expose the retired authoring workflow')
assert.doesNotMatch(storeSource, /initAgentBook|buildAgentStructure|fetchAgentManifest|fetchAgentHistory|confirmAgentStructure|regenerateAgentNode|interactWithAgent|\/agent\//, 'Book store should not retain retired authoring actions')
assert.doesNotMatch(source, /Macros saved|Prompt Macros|>\s*Macros\s*</, 'Library should not present legacy prompt macro language')
assert.match(source, /preflightWarning/, 'Library should track import preflight warnings')
assert.match(source, /outlineReview/, 'Library should track import outline confirmation')
assert.match(source, /confirmOutlineImport/, 'Library should confirm user-selected outline split points')
assert.match(source, /outlinePlan/, 'Library should preserve the confirmed outline plan across preflight confirmation')
assert.match(storeSource, /outline_plan/, 'Book store should send outline plans to the backend')
assert.match(source, /confirmPreflightImport/, 'Library should provide a force-import confirmation handler')
assert.match(source, /force:\s*true/, 'Library should retry imports with force after confirmation')
assert.match(storeSource, /async fetchLearningProfile\(bookId\)/, 'Book store should expose learning profile fetch action')
assert.match(storeSource, /`\/books\/\$\{bookId\}\/quiz\/profile`/, 'Book store should call the profile markdown endpoint')
assert.match(source, /data-tooltip="Quiz · 学习画像"/, 'Library cards should expose the dedicated learning workspace')
assert.match(source, /data-tooltip="内容状态"/, 'Library cards should expose content status outside the menu')
assert.match(source, /data-tooltip="笔记"/, 'Library cards should expose notes outside the menu')
assert.match(source, /画像待更新/, 'Library should show a compact pending-profile signal')
assert.match(source, /name: 'book-management'/, 'each library book should link to its management workspace')
assert.match(source, /name: 'book-learning'/, 'each library book should link to its learning workspace')
assert.match(source, /target="_blank"/, 'secondary book workspaces should open in new tabs')
assert.match(storeSource, /async generateBookGuides\(id\)/, 'book store should expose background guide generation for existing books')
assert.match(source, /openBookMenuId/, 'Library should group secondary book actions in a discoverable menu')
assert.match(source, /导出图书包/, 'Library management menu should group export with rename and delete')
assert.match(source, /bookStore\.exportBookPackage\(book\.id/, 'Library menu export should download the selected book')
assert.doesNotMatch(source, /Analyze Learning Profile|View Learning Profile|生成 \/ 重新生成导读/, 'Library menu should not duplicate status and learning workspace actions')
assert.doesNotMatch(source, /library-catalog-bar|全部书目|<dt>藏书<\/dt>|<dt>已完成<\/dt>|<dt>处理中<\/dt>/, 'Library should not repeat collection statistics above the cards')
assert.match(source, /formatBookIndex/, 'Library cards should expose stable volume numbering')
assert.match(source, /formatLibraryBookTitle/, 'Library cards should clean generated filenames for display')
assert.match(source, /return isTranslating\(book\)/, 'Library should only show translation progress while a translation is active')
assert.match(source, /requestDeleteBook/, 'Library should use an in-app delete confirmation flow')
assert.doesNotMatch(source, /\b(?:alert|confirm)\s*\(/, 'Library should not use blocking browser alert or confirm dialogs')

console.log('Library response style entry point ok')
