import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, resolve } from 'node:path'

const currentDir = dirname(fileURLToPath(import.meta.url))
const source = readFileSync(resolve(currentDir, 'Reader.vue'), 'utf8')

assert.doesNotMatch(source, /await bookStore\.fetchNextQuizQuestion/, 'Reader should not wait for Quiz generation before opening the conversation page')
assert.match(source, /createPendingQuizCard/, 'Reader Quiz should create a visible pending card before requesting a question')
assert.match(source, /openConversationPage\(card, \{ quizRequest \}\)/, 'Reader should hand question generation to the new Quiz page')
assert.match(source, /if \(options\.quizRequest\)[\s\S]*?window\.open/, 'Reader should open the Quiz page synchronously from the click path')
assert.match(source, /questionType:\s*String\(route\.query\.question_type/, 'Reader should use Book Quiz selected question type')
assert.match(source, /quizMode:\s*String\(route\.query\.quiz_mode \|\| 'book'\)/, 'Reader should explicitly preserve Book Quiz mode')
assert.match(source, /buildReaderItemQuery/, 'Reader should write selected reader identity into the URL query')
assert.match(source, /findReaderLeafByRouteQuery/, 'Reader should resolve initial content from explicit reader URL params')
assert.match(source, /router\.replace/, 'Reader should keep chapter and guide selection reflected in the current GET URL')
assert.match(source, /bookQuizTarget:\$\{book\.value\.id\}/, 'Reader should read the Book Quiz personalization payload')
assert.match(source, /Target concept: \$\{parsed\.target_concept\}/, 'Reader should pass the selected Book Quiz target concept into personalization context')
assert.match(source, /Reason: \$\{parsed\.reason\}/, 'Reader should pass the Book Quiz selection reason into personalization context')
assert.match(source, /openLatexRepairDialog/, 'Reader should open a LaTeX repair dialog from selected text')
assert.match(source, /retryLatexRepair/, 'Reader should let users retry failed LaTeX repair candidates')
assert.match(source, /confirmLatexRepair/, 'Reader should apply the confirmed LaTeX repair candidate')
assert.match(source, /latexRepair\.value\.failedCandidates/, 'Reader should send failed repair candidates back for retry context')
assert.match(source, /findChapterGuideLeaf/, 'Reader should resolve the guide matching the current chapter')
assert.match(source, /guide-dual/, 'Reader should support a chapter-plus-guide dual pane mode')
assert.match(source, /renderedGuide/, 'Reader should render matched chapter guide content separately from chapter content')
assert.doesNotMatch(source, /learningPreviewToMarkdown|fetchChapterLearning/, 'Reader should not load or render Learning Context')
assert.match(source, /readerType:\s*'guide'/, 'Guide dual pane should load only generated guides')
assert.match(source, /setViewMode/, 'Reader should use explicit view mode selection instead of cycling pane modes')
assert.match(source, /canUseChapterContent/, 'Reader should allow guide dual whenever the selected item carries a chapter id')
assert.match(source, /loadItemFromRouteQuery/, 'Reader should load content from reader URL query after initial mount')
assert.match(source, /getFurthestReadChapter/, 'Reader should restore the furthest chapter when opened without an explicit target')
assert.match(source, /hasExplicitReaderTarget[\s\S]*?findReaderLeafByRouteQuery/, 'explicit chapter and guide deep links should override automatic resume')
assert.match(source, /rememberFurthestReadChapter/, 'Reader should update furthest reading progress as chapters open')
assert.match(source, /checkLearningProfileInBackground/, 'Reader should check the optional learning profile on entry')
assert.match(source, /getBookChapterReadingStatuses/, 'Reader should sync per-chapter reading state with the profile check')
assert.match(source, /route\.query\.chapter_id/, 'Reader should react when the chapter_id query changes on the same reader route')
assert.match(source, /sidebarOpen/, 'Reader should let the toolbar collapse the table of contents')
assert.match(source, /focusRouteNote/, 'Reader should restore and highlight a note opened from the Notes page')
assert.match(source, /route\.query\.note_id/, 'Reader should accept explicit note deep links')
assert.match(source, /card\?\.contextScope === 'selection'/, 'selection-only notes should send only selected text as chat context')
assert.match(source, /fetchReaderContent\(book\.value\.id, \{[\s\S]*?readerType: 'chapter'/, 'chapter notes should load complete chapter Markdown for chat context')
assert.match(source, /content_translated/, 'chapter note context should prefer the complete translated chapter when available')
assert.match(source, /return body/, 'chapter chat should send the complete imported chapter body')
assert.doesNotMatch(source, /compactChapterBody/, 'chapter chat should not apply a second context-length limit')
assert.match(source, /action === 'chapter-note'[\s\S]*?createChapterCard/, 'selected text can seed a whole-chapter question without shrinking the context')
assert.match(source, /ensureSelectionCard\(currentToolSubject\.value, text\)/, 'selection questions should keep selected text as context without prefilling the composer')
assert.doesNotMatch(source, /ensureSelectionCard\(currentToolSubject\.value, text, \{ initialPrompt: text \}\)/, 'selection questions should not duplicate selected text in the composer')
assert.match(source, /@go-next="goToNextReaderItem"/, 'next-page navigation should run the reading completion check')
assert.match(source, /readingPercent\.value >= 100[\s\S]*?progress: 'finished'[\s\S]*?goToReaderItem\(nextReaderItem\.value\)/, 'a fully read chapter should be marked finished before opening the next item')
assert.match(source, /source-note-highlight--selection[\s\S]*?var\(--color-selection-soft\)/, 'saved selection highlights should use the same calm blue selection palette')
assert.match(source, /bookStore\.createAnnotation/, 'reader annotations should be persisted through the book store')
assert.match(source, /notes\.filter\(\(note\) => note\.type === 'annotation'\)/, 'reader should restore saved annotations from source notes')
assert.match(source, /renderRevision\.value === 0/, 'annotations should wait until Markdown and math rendering have completed')
assert.match(source, /reader-annotation--highlight[\s\S]*?rgba\(247, 218, 92, 0\.48\)/, 'traditional highlights should use a restrained yellow treatment')
assert.match(source, /reader-annotation--underline[\s\S]*?text-decoration-line:\s*underline/, 'traditional underline annotations should render as underlined text')

const globalStyles = readFileSync(resolve(currentDir, '../style.css'), 'utf8')
const designSystem = readFileSync(resolve(currentDir, '../design-system.css'), 'utf8')
assert.match(globalStyles, /::selection\s*\{[\s\S]*?var\(--color-selection-soft\)/, 'native text selections should use the dedicated blue selection color')
assert.match(designSystem, /#app \.selected-text-preview\s*\{[\s\S]*?var\(--color-selection-soft\)/, 'saved text selections should use the dedicated blue selection color')
assert.match(designSystem, /#app \.question-block\s*\{[\s\S]*?var\(--color-question-soft\)/, 'Note questions should use a quiet neutral surface instead of the brand accent')
assert.match(designSystem, /#app \.status-difficulty-unmarked/, 'unmarked should be the neutral default difficulty treatment')
assert.match(globalStyles, /\.latex-content strong\s*\{[\s\S]*?font-weight:\s*700;[\s\S]*?var\(--color-emphasis-mark\)/, 'Markdown bold text should have a clearly visible editorial emphasis treatment')
assert.match(globalStyles, /\.latex-content \.katex-display > \.katex > \.katex-html\s*\{[\s\S]*?display:\s*flex;[\s\S]*?flex-wrap:\s*wrap;/, 'long display formulas should wrap inside the reading column instead of requiring horizontal scrolling')

const panesSource = readFileSync(resolve(currentDir, '../components/ReaderPanes.vue'), 'utf8')
assert.match(panesSource, /No chapter guide is available for this chapter yet\./, 'Guide dual pane should keep the missing-guide empty state')
assert.match(panesSource, /props\.viewMode === 'guide-dual'\) return 'guide-dual'/, 'Guide dual pane should not fall back to single just because source HTML is empty')
assert.match(panesSource, /guideUnavailable/, 'Guide dual pane should show the empty state when the right pane has no rendered guide HTML')
assert.match(panesSource, /leftPaneHtml/, 'Guide dual pane should be able to use a different left pane source than translation dual')
assert.match(panesSource, /syncPaneScroll/, 'Dual panes should synchronize their scroll position')
assert.match(panesSource, /scroll-progress/, 'Reader panes should report chapter reading progress')

const contentSource = readFileSync(resolve(currentDir, '../composables/useReaderContent.js'), 'utf8')
assert.match(contentSource, /data\.content_translated === 'string' && data\.content_translated\.trim\(\)/, 'Reader content should fall back to raw chapter content when translated content is blank')
assert.match(contentSource, /Failed to load guide chapter context/, 'Guide content should load same-chapter context without blocking guide display')
assert.doesNotMatch(contentSource, /loadLearning|readerType:\s*'learning'/, 'Reader content should support only chapters and generated guides')

console.log('Reader structured quiz wiring ok')
